apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-db-secret
  namespace: techx-tf4
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: postgres-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: techx/tf4/postgres
        property: password
    - secretKey: username
      remoteRef:
        key: techx/tf4/postgres
        property: username

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-smtp-secret
  namespace: techx-observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: alertmanager-smtp-auth
    creationPolicy: Owner
  data:
    - secretKey: smtp-password
      remoteRef:
        key: techx/tf4/alertmanager
        property: smtp-password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openai-api-secret
  namespace: techx-tf4
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: openai-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: techx/tf4/openai
        property: api-key

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: techx-observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: techx/tf4/grafana
        property: admin-password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flagd-bearer-secret
  namespace: techx-tf4
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: flagd-bearer-token
    creationPolicy: Owner
  data:
    - secretKey: bearer-token
      remoteRef:
        key: techx/tf4/flagd
        property: bearer-token

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: msk-kafka-secret
  namespace: techx-tf4
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: msk-kafka-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: kafka-address
      remoteRef:
        key: techx/tf4/msk-kafka
        property: bootstrap_servers
    - secretKey: security-protocol
      remoteRef:
        key: techx/tf4/msk-kafka
        property: security_protocol
    - secretKey: sasl-mechanism
      remoteRef:
        key: techx/tf4/msk-kafka
        property: sasl_mechanism
    - secretKey: username
      remoteRef:
        key: techx/tf4/msk-kafka
        property: username
    - secretKey: password
      remoteRef:
        key: techx/tf4/msk-kafka
        property: password
