apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: techx-production
  source:
    repoURL: 'https://charts.external-secrets.io'
    chart: external-secrets
    targetRevision: 0.9.20
    helm:
      values: |
        installCRDs: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: techx-production
  source:
    repoURL: 'https://github.com/TF4-Phase3-TechX/tf4-phase3-gitops-manifests.git'
    targetRevision: HEAD
    path: platform/secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: techx-tf4
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techx-raw
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: techx-production
  source:
    repoURL: 'https://github.com/TF4-Phase3-TechX/tf4-phase3-gitops-manifests.git'
    targetRevision: HEAD
    path: environments/production/raw
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: techx-tf4
  syncPolicy:
    automated:
      prune: false
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techx-observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: techx-production
  sources:
    - repoURL: 'https://github.com/TF4-Phase3-TechX/tf4-phase3-repo.git'
      targetRevision: 1b03bfe0b6316ffa15dd58486752920f4b295db1
      path: techx-corp-chart
      ref: chart-source
      helm:
        releaseName: techx-observability
        valueFiles:
          - '$values-source/environments/production/observability-values.yaml'
          - '$values-source/environments/production/alertmanager-routing-values.yaml'
    - repoURL: 'https://github.com/TF4-Phase3-TechX/tf4-phase3-gitops-manifests.git'
      targetRevision: main
      ref: values-source
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: techx-observability
  syncPolicy:
    syncOptions:
      - FailOnSharedResource=true
      - ApplyOutOfSyncOnly=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techx-corp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: techx-production
  sources:
    - repoURL: 'https://github.com/TF4-Phase3-TechX/tf4-phase3-repo.git'
      targetRevision: 1b03bfe0b6316ffa15dd58486752920f4b295db1
      path: techx-corp-chart
      ref: chart-source
      helm:
        releaseName: techx-corp
        valueFiles:
          - '$values-source/environments/production/app-values.yaml'
          - '$values-source/environments/production/flagd-values.yaml'
          - '$values-source/environments/production/image-revisions.yaml'
    - repoURL: 'https://github.com/TF4-Phase3-TechX/tf4-phase3-gitops-manifests.git'
      targetRevision: main
      ref: values-source
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: techx-tf4
  syncPolicy:
    syncOptions:
      - FailOnSharedResource=true
      - ApplyOutOfSyncOnly=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
