prometheus:
  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
      route:
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 1h
        receiver: 'email-notifications'
      receivers:
      - name: 'email-notifications'
        email_configs:
        - to: 'recipient@techx.corp'
          from: 'alertmanager@techx.corp'
          smarthost: 'smtp.mailtrap.io:2525'
          auth_username: 'api'
          auth_password_file: '/etc/alertmanager/secrets/smtp-password'
        slack_configs:
        - api_url_file: /etc/alertmanager/slack/webhook-url
          send_resolved: true

