apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-opensearch-0
  namespace: techx-observability
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 40Gi
