apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus
  namespace: techx-observability
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3-retain
  resources:
    requests:
      storage: 20Gi
